### ISSUE TITLE
WEB: Go Gorm docs

### ISSUE THREAD

**Issue by developerasun** [asunlabs/awesome-engineer-courses#5]
## Sub-tasks

**Getting Started**
- [x] Overview
- [x] Declaring Models
- [x] Connecting to Database

**CRUD Interface**
- [x] Create
- [x] Query
- [ ] Advanced Query
- [x] Update
- [x] Delete
- [ ] Raw SQL & SQL Builder

**Associations**
- [x] Belongs To
- [x] Has One
- [x] Has Many
- [x] Many To Many
- [x] Association Mode
- [x] Preloading (Eager Loading)

**Tutorials**
- [x] Context
- [x] Error Handling
- [ ] Method Chaining
- [ ] Session
- [ ] Hooks
- [ ] Transactions
- [ ] Migration
- [ ] Logger
- [ ] Generic Database Interface
- [ ] Performance
- [ ] Customize Data Types
- [ ] Scopes
- [ ] Conventions
- [ ] Settings

**Advanced Topics**
- [ ] Database Resolver
- [ ] Sharding
- [ ] Serializer
- [ ] Prometheus
- [ ] Hints
- [ ] Indexes
- [ ] Constraints
- [ ] Composite Primary Key
- [ ] Security
- [ ] GORM Config
- [ ] Write Plugins
- [ ] Write Driver
- [ ] ChangeLog
- [ ] Community
- [ ] Contribute
- [ ] Translate current site
